name = "werc"
license = "CC0-1.0"
licenselink = "https://github.com/ctis-me/hugo-werc"
description = "A theme ported from werc"
homepage = "https://github.com/ctis-me/hugo-werc"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Dennis Lee, Charlton Trezevant"
  homepage = "https://github.com/ctis-me/hugo-werc"

[original]
  name = "werc"
  homepage = "http://werc.cat-v.org/"
  repo = "https://code.9front.org/hg/werc"
